/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoCreateRouteImport } from './routes/demo.create'
import { Route as DemoHistoryRouteImport } from './routes/demo.history'
import { Route as DemoPaymentIdRouteImport } from './routes/demo.payment.$id'
import { Route as DemoRecoveryIdCheckoutRouteImport } from './routes/demo.recovery.$id.checkout'
import { Route as DemoRecoveryIdResultRouteImport } from './routes/demo.recovery.$id.result'
import { Route as DemoRecoveryIdVerifyRouteImport } from './routes/demo.recovery.$id.verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoCreateRoute = DemoCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DemoRoute,
} as any)
const DemoHistoryRoute = DemoHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPaymentIdRoute = DemoPaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRecoveryIdCheckoutRoute = DemoRecoveryIdCheckoutRouteImport.update({
  id: '/recovery/$id/checkout',
  path: '/recovery/$id/checkout',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRecoveryIdResultRoute = DemoRecoveryIdResultRouteImport.update({
  id: '/recovery/$id/result',
  path: '/recovery/$id/result',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRecoveryIdVerifyRoute = DemoRecoveryIdVerifyRouteImport.update({
  id: '/recovery/$id/verify',
  path: '/recovery/$id/verify',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/create': typeof DemoCreateRoute
  '/demo/history': typeof DemoHistoryRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/payment/$id': typeof DemoPaymentIdRoute
  '/demo/recovery/$id/checkout': typeof DemoRecoveryIdCheckoutRoute
  '/demo/recovery/$id/result': typeof DemoRecoveryIdResultRoute
  '/demo/recovery/$id/verify': typeof DemoRecoveryIdVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/create': typeof DemoCreateRoute
  '/demo/history': typeof DemoHistoryRoute
  '/demo': typeof DemoIndexRoute
  '/demo/payment/$id': typeof DemoPaymentIdRoute
  '/demo/recovery/$id/checkout': typeof DemoRecoveryIdCheckoutRoute
  '/demo/recovery/$id/result': typeof DemoRecoveryIdResultRoute
  '/demo/recovery/$id/verify': typeof DemoRecoveryIdVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/create': typeof DemoCreateRoute
  '/demo/history': typeof DemoHistoryRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/payment/$id': typeof DemoPaymentIdRoute
  '/demo/recovery/$id/checkout': typeof DemoRecoveryIdCheckoutRoute
  '/demo/recovery/$id/result': typeof DemoRecoveryIdResultRoute
  '/demo/recovery/$id/verify': typeof DemoRecoveryIdVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/demo/create'
    | '/demo/history'
    | '/demo/'
    | '/demo/payment/$id'
    | '/demo/recovery/$id/checkout'
    | '/demo/recovery/$id/result'
    | '/demo/recovery/$id/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/create'
    | '/demo/history'
    | '/demo'
    | '/demo/payment/$id'
    | '/demo/recovery/$id/checkout'
    | '/demo/recovery/$id/result'
    | '/demo/recovery/$id/verify'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/demo/create'
    | '/demo/history'
    | '/demo/'
    | '/demo/payment/$id'
    | '/demo/recovery/$id/checkout'
    | '/demo/recovery/$id/result'
    | '/demo/recovery/$id/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/create': {
      id: '/demo/create'
      path: '/create'
      fullPath: '/demo/create'
      preLoaderRoute: typeof DemoCreateRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/history': {
      id: '/demo/history'
      path: '/history'
      fullPath: '/demo/history'
      preLoaderRoute: typeof DemoHistoryRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/payment/$id': {
      id: '/demo/payment/$id'
      path: '/payment/$id'
      fullPath: '/demo/payment/$id'
      preLoaderRoute: typeof DemoPaymentIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/recovery/$id/checkout': {
      id: '/demo/recovery/$id/checkout'
      path: '/recovery/$id/checkout'
      fullPath: '/demo/recovery/$id/checkout'
      preLoaderRoute: typeof DemoRecoveryIdCheckoutRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/recovery/$id/result': {
      id: '/demo/recovery/$id/result'
      path: '/recovery/$id/result'
      fullPath: '/demo/recovery/$id/result'
      preLoaderRoute: typeof DemoRecoveryIdResultRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/recovery/$id/verify': {
      id: '/demo/recovery/$id/verify'
      path: '/recovery/$id/verify'
      fullPath: '/demo/recovery/$id/verify'
      preLoaderRoute: typeof DemoRecoveryIdVerifyRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface DemoRouteChildren {
  DemoCreateRoute: typeof DemoCreateRoute
  DemoHistoryRoute: typeof DemoHistoryRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoPaymentIdRoute: typeof DemoPaymentIdRoute
  DemoRecoveryIdCheckoutRoute: typeof DemoRecoveryIdCheckoutRoute
  DemoRecoveryIdResultRoute: typeof DemoRecoveryIdResultRoute
  DemoRecoveryIdVerifyRoute: typeof DemoRecoveryIdVerifyRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoCreateRoute: DemoCreateRoute,
  DemoHistoryRoute: DemoHistoryRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoPaymentIdRoute: DemoPaymentIdRoute,
  DemoRecoveryIdCheckoutRoute: DemoRecoveryIdCheckoutRoute,
  DemoRecoveryIdResultRoute: DemoRecoveryIdResultRoute,
  DemoRecoveryIdVerifyRoute: DemoRecoveryIdVerifyRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
